/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_DominantColourInterface */

#ifndef _Included_libraryInterfaces_DominantColourInterface
#define _Included_libraryInterfaces_DominantColourInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_DominantColourInterface
 * Method:    applyDominantColour
 * Signature: ([[LlibraryInterfaces/Pixel;)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_DominantColourInterface_applyDominantColour
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
