/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_BrightnessInterface */

#ifndef _Included_libraryInterfaces_BrightnessInterface
#define _Included_libraryInterfaces_BrightnessInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_BrightnessInterface
 * Method:    applyBrightness
 * Signature: ([[LlibraryInterfaces/Pixel;F)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_BrightnessInterface_applyBrightness
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
