/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_HueSaturationInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_HueSaturationInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_HueSaturationInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_HueSaturationInterface
 * Method:    applyHueSaturation
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;FF)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_HueSaturationInterface_applyHueSaturation
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
