/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_SharpenInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_SharpenInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_SharpenInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_SharpenInterface
 * Method:    applySharpen
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;F)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_SharpenInterface_applySharpen
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
