/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_driveProject_libraryInterfaces_InvertInterface */

#ifndef _Included_com_iiitb_driveProject_libraryInterfaces_InvertInterface
#define _Included_com_iiitb_driveProject_libraryInterfaces_InvertInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_driveProject_libraryInterfaces_InvertInterface
 * Method:    applyInvert
 * Signature: ([[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;)[[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_driveProject_libraryInterfaces_InvertInterface_applyInvert
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
