/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_driveProject_libraryInterfaces_FlipInterface */

#ifndef _Included_com_iiitb_driveProject_libraryInterfaces_FlipInterface
#define _Included_com_iiitb_driveProject_libraryInterfaces_FlipInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_driveProject_libraryInterfaces_FlipInterface
 * Method:    applyFlip
 * Signature: ([[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;II)[[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_driveProject_libraryInterfaces_FlipInterface_applyFlip
  (JNIEnv *, jclass, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
