/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_BrightnessInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_BrightnessInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_BrightnessInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_BrightnessInterface
 * Method:    applyBrightness
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;F)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_BrightnessInterface_applyBrightness
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
