/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_SharpenInterface */

#ifndef _Included_libraryInterfaces_SharpenInterface
#define _Included_libraryInterfaces_SharpenInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_SharpenInterface
 * Method:    applySharpen
 * Signature: ([[LlibraryInterfaces/Pixel;F)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_SharpenInterface_applySharpen
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
