/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_driveProject_libraryInterfaces_SepiaInterface */

#ifndef _Included_com_iiitb_driveProject_libraryInterfaces_SepiaInterface
#define _Included_com_iiitb_driveProject_libraryInterfaces_SepiaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_driveProject_libraryInterfaces_SepiaInterface
 * Method:    applySepia
 * Signature: ([[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;)[[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_driveProject_libraryInterfaces_SepiaInterface_applySepia
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
