/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_driveProject_libraryInterfaces_ContrastInterface */

#ifndef _Included_com_iiitb_driveProject_libraryInterfaces_ContrastInterface
#define _Included_com_iiitb_driveProject_libraryInterfaces_ContrastInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_driveProject_libraryInterfaces_ContrastInterface
 * Method:    applyContrast
 * Signature: ([[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;F)[[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_driveProject_libraryInterfaces_ContrastInterface_applyContrast
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
