/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_GaussianBlurInterface */

#ifndef _Included_libraryInterfaces_GaussianBlurInterface
#define _Included_libraryInterfaces_GaussianBlurInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_GaussianBlurInterface
 * Method:    applyGaussianBlur
 * Signature: ([[LlibraryInterfaces/Pixel;F)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_GaussianBlurInterface_applyGaussianBlur
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
