/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_driveProject_libraryInterfaces_GaussianBlurInterface */

#ifndef _Included_com_iiitb_driveProject_libraryInterfaces_GaussianBlurInterface
#define _Included_com_iiitb_driveProject_libraryInterfaces_GaussianBlurInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_driveProject_libraryInterfaces_GaussianBlurInterface
 * Method:    applyGaussianBlur
 * Signature: ([[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;F)[[Lcom/iiitb/driveProject/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_driveProject_libraryInterfaces_GaussianBlurInterface_applyGaussianBlur
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
