/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_ContrastInterface */

#ifndef _Included_libraryInterfaces_ContrastInterface
#define _Included_libraryInterfaces_ContrastInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_ContrastInterface
 * Method:    applyContrast
 * Signature: ([[LlibraryInterfaces/Pixel;F)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_ContrastInterface_applyContrast
  (JNIEnv *, jclass, jobjectArray, jfloat);

#ifdef __cplusplus
}
#endif
#endif
