/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_FlipInterface */

#ifndef _Included_libraryInterfaces_FlipInterface
#define _Included_libraryInterfaces_FlipInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_FlipInterface
 * Method:    applyFlip
 * Signature: ([[LlibraryInterfaces/Pixel;II)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_FlipInterface_applyFlip
  (JNIEnv *, jclass, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
