/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_InvertInterface */

#ifndef _Included_libraryInterfaces_InvertInterface
#define _Included_libraryInterfaces_InvertInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_InvertInterface
 * Method:    applyInvert
 * Signature: ([[LlibraryInterfaces/Pixel;)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_InvertInterface_applyInvert
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
