/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_HueSaturationInterface */

#ifndef _Included_libraryInterfaces_HueSaturationInterface
#define _Included_libraryInterfaces_HueSaturationInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_HueSaturationInterface
 * Method:    applyHueSaturation
 * Signature: ([[LlibraryInterfaces/Pixel;FF)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_HueSaturationInterface_applyHueSaturation
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
