/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_RotationInterface */

#ifndef _Included_libraryInterfaces_RotationInterface
#define _Included_libraryInterfaces_RotationInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_RotationInterface
 * Method:    applyRotation
 * Signature: ([[LlibraryInterfaces/Pixel;I)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_RotationInterface_applyRotation
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
