/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iiitb_imageEffectApplication_libraryInterfaces_RotationInterface */

#ifndef _Included_com_iiitb_imageEffectApplication_libraryInterfaces_RotationInterface
#define _Included_com_iiitb_imageEffectApplication_libraryInterfaces_RotationInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iiitb_imageEffectApplication_libraryInterfaces_RotationInterface
 * Method:    applyRotation
 * Signature: ([[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;I)[[Lcom/iiitb/imageEffectApplication/libraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_iiitb_imageEffectApplication_libraryInterfaces_RotationInterface_applyRotation
  (JNIEnv *, jclass, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
