/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_SepiaInterface */

#ifndef _Included_libraryInterfaces_SepiaInterface
#define _Included_libraryInterfaces_SepiaInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_SepiaInterface
 * Method:    applySepia
 * Signature: ([[LlibraryInterfaces/Pixel;)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_SepiaInterface_applySepia
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
