/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libraryInterfaces_GrayscaleInterface */

#ifndef _Included_libraryInterfaces_GrayscaleInterface
#define _Included_libraryInterfaces_GrayscaleInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libraryInterfaces_GrayscaleInterface
 * Method:    applyGrayscale
 * Signature: ([[LlibraryInterfaces/Pixel;FF)[[LlibraryInterfaces/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_libraryInterfaces_GrayscaleInterface_applyGrayscale
  (JNIEnv *, jclass, jobjectArray, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
